### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by quinox**
As discussed with @mpvader : Automatic running of testcases based on Travis.

Preview: https://travis-ci.org/quinox/velib_python/builds/119823327

How to use:
* Visit https://travis-ci.org/
* Click "Sign in with GitHub" on the top right, grant API permissions to Travis
* Inside Travis, enable CI for the velib_python project
* Merge this PR with an updated badge URL: https://travis-ci.org/victronenergy/velib_python.svg?branch=master

### CODE REVIEW

**Comment by edevries-victron** [comment]
Pull request has been accepted by cherry-picking instead of merging.

**Comment by quinox** [comment]
Thanks! The badge URL still points to my fork though (https://raw.githubusercontent.com/victronenergy/velib_python/master/README.md, line 4)

**Comment by edevries-victron** [comment]
Sorry. Do I need to change both url’s in [Build Status] or the first one only?

[Build Status](https://travis-ci.org/quinox/velib_python)<https://travis-ci.org/quinox/velib_python.svg?branch=travis)%5d(https://travis-ci.org/quinox/velib_python)>

**Comment by quinox** [comment]
Both need to be changed: the first one is used for the image of the badge and the second one is used for the `href` of the badge.

The correct code can also be retrieved from the Travis interface, see [this page](https://docs.travis-ci.com/user/status-images/)

**Pull request closed without merging**
